services:
  traefik:
    image: traefik:v3.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=DEBUG
      - --accesslog
      - --experimental.localPlugins.fail2ban-local.moduleName=github.com/MaxGridasoff/fail2ban
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/plugins-local/src/github.com/MaxGridasoff/fail2ban/
    tty: true

  whoami:
    depends_on:
      - traefik
    image: traefik/whoami # https://github.com/traefik/whoami
    command: >-
      -name whoami -verbose true
    labels:
      traefik.http.routers.fail2ban-local.rule: Host(`fail2ban-local.localhost`)
      traefik.http.routers.fail2ban-local.middlewares: fail2ban-local
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.enabled: true
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.bantime: 3h
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.findtime: 3h
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.maxretry: 4
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.allowlist.ipheader: "X-Real-Ip"
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.allowlist.ip[0]: 127.0.0.2
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.allowlist.ip[1]: 192.168.0.35
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.denylist.ip[0]: 127.0.0.1
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.denylist.ip[1]: 172.21.0.1
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.urlregexps[0].regexp: /no
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.urlregexps[0].mode: block
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.urlregexps[1].regexp: /yes
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.urlregexps[1].mode: allow
      traefik.http.middlewares.fail2ban-local.plugin.fail2ban-local.rules.statuscode: "400,401,403-499"

      traefik.http.middlewares.fail2ban-registery.plugin.fail2ban-registery.enabled: true
